/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayReflexRouteImport } from './routes/play.reflex'
import { Route as PlayMemoryRouteImport } from './routes/play.memory'
import { Route as PlayBalanceRouteImport } from './routes/play.balance'

const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReflexRoute = PlayReflexRouteImport.update({
  id: '/play/reflex',
  path: '/play/reflex',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMemoryRoute = PlayMemoryRouteImport.update({
  id: '/play/memory',
  path: '/play/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBalanceRoute = PlayBalanceRouteImport.update({
  id: '/play/balance',
  path: '/play/balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/play/balance'
    | '/play/memory'
    | '/play/reflex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/challenges' | '/play/balance' | '/play/memory' | '/play/reflex'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/play/balance'
    | '/play/memory'
    | '/play/reflex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  PlayBalanceRoute: typeof PlayBalanceRoute
  PlayMemoryRoute: typeof PlayMemoryRoute
  PlayReflexRoute: typeof PlayReflexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/reflex': {
      id: '/play/reflex'
      path: '/play/reflex'
      fullPath: '/play/reflex'
      preLoaderRoute: typeof PlayReflexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/memory': {
      id: '/play/memory'
      path: '/play/memory'
      fullPath: '/play/memory'
      preLoaderRoute: typeof PlayMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/balance': {
      id: '/play/balance'
      path: '/play/balance'
      fullPath: '/play/balance'
      preLoaderRoute: typeof PlayBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  PlayBalanceRoute: PlayBalanceRoute,
  PlayMemoryRoute: PlayMemoryRoute,
  PlayReflexRoute: PlayReflexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
