/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RetrieveRouteImport } from './routes/retrieve'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminUserUserIdRouteImport } from './routes/admin.user.$userId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayReflexRouteImport } from './routes/play.reflex'
import { Route as PlayMemoryRouteImport } from './routes/play.memory'
import { Route as PlayBalanceRouteImport } from './routes/play.balance'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrieveRoute = RetrieveRouteImport.update({
  id: '/retrieve',
  path: '/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/admin/user/$userId',
  path: '/admin/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReflexRoute = PlayReflexRouteImport.update({
  id: '/play/reflex',
  path: '/play/reflex',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMemoryRoute = PlayMemoryRouteImport.update({
  id: '/play/memory',
  path: '/play/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBalanceRoute = PlayBalanceRouteImport.update({
  id: '/play/balance',
  path: '/play/balance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/retrieve': typeof RetrieveRoute
  '/terms': typeof TermsRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/retrieve': typeof RetrieveRoute
  '/terms': typeof TermsRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/retrieve': typeof RetrieveRoute
  '/terms': typeof TermsRoute
  '/play/balance': typeof PlayBalanceRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/reflex': typeof PlayReflexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/user/$userId'
    | '/auth'
    | '/challenges'
    | '/privacy'
    | '/profile'
    | '/result'
    | '/retrieve'
    | '/terms'
    | '/play/balance'
    | '/play/memory'
    | '/play/reflex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/user/$userId'
    | '/auth'
    | '/challenges'
    | '/privacy'
    | '/profile'
    | '/result'
    | '/retrieve'
    | '/terms'
    | '/play/balance'
    | '/play/memory'
    | '/play/reflex'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/user/$userId'
    | '/auth'
    | '/challenges'
    | '/privacy'
    | '/profile'
    | '/result'
    | '/retrieve'
    | '/terms'
    | '/play/balance'
    | '/play/memory'
    | '/play/reflex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  RetrieveRoute: typeof RetrieveRoute
  TermsRoute: typeof TermsRoute
  PlayBalanceRoute: typeof PlayBalanceRoute
  PlayMemoryRoute: typeof PlayMemoryRoute
  PlayReflexRoute: typeof PlayReflexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieve': {
      id: '/retrieve'
      path: '/retrieve'
      fullPath: '/retrieve'
      preLoaderRoute: typeof RetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/admin/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/reflex': {
      id: '/play/reflex'
      path: '/play/reflex'
      fullPath: '/play/reflex'
      preLoaderRoute: typeof PlayReflexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/memory': {
      id: '/play/memory'
      path: '/play/memory'
      fullPath: '/play/memory'
      preLoaderRoute: typeof PlayMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/balance': {
      id: '/play/balance'
      path: '/play/balance'
      fullPath: '/play/balance'
      preLoaderRoute: typeof PlayBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  RetrieveRoute: RetrieveRoute,
  TermsRoute: TermsRoute,
  PlayBalanceRoute: PlayBalanceRoute,
  PlayMemoryRoute: PlayMemoryRoute,
  PlayReflexRoute: PlayReflexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
